language: ruby
cache: bundler
services:
- postgresql
- redis-server
before_script:
- psql -c 'create database operationcode_test;' -U postgres
- RAILS_ENV=test bundle exec rake db:migrate
- RAILS_ENV=test bundle exec rake db:test:prepare
- RAILS_ENV=test bundle exec rake db:fixtures:load
after_success: 
- cd blog && bundle install --gemfile=./Gemfile --binstubs
- cd bin && jekyll build --config ../_config.yml --destination ../../public/blog
- cd ../..
deploy:
  provider: heroku
  api_key:
    secure: IjVV/RT2ewpGGM3/lX3mjEzroHzKWVNMKQJTQK/i/z2dOA2bmxFHvqLP1cvuiW7LAyzvCiIbTflDr1kyIQnBUlIfHWgQCwAFbhL74FxnNYznZ6eDovtlkV9a/2Xq6CEX0BdFtbyGEXWto+zqO+R0iXEZ4suaswzRxKBde4RXG1I=
  app: opcod3
  on:
    repo: OperationCode/operationcode
  run:
    "rake db:migrate"
  skip_cleanup: true
notifications:
  slack:
    secure: iT5O6nPXUfThuPLhLXY1q6iNPrJfXxwv78ZynDiZZ2HjUqk98F7LTLY4dAXabbPL2w4hY9YcE8gTXch5n+eyjIaCSNHiR6VMJuxdhiw7uolAy5F71rEMyhNmZbe7X+lqNTp5GpoBUU2oCrT3Hh30lE8Z3c1XrQ+hvm0vh7Y1hXs=
env:
  secure: "AmnH0r1tF9HIVsUfhoJHzCEqTZz3TU4FUd2D+T0XzSDbz6kUSubmP4agYRsJI1xPTwegqSonwL0QGAlaIKEssz6rqAqBSvzHC95XvghP1HVVp2/j8vvFaJbpWsnTQ25FbMgDD89wHRKRs0qk2Ui0zi+CtNFylj83D13yoVys6C0="
